# Generated by Django 4.0.5 on 2023-04-08 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=70)),
                ('product_price', models.CharField(max_length=20)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product')),
                ('product_image2', models.ImageField(blank=True, null=True, upload_to='product')),
                ('product_image3', models.ImageField(blank=True, null=True, upload_to='product')),
                ('product_image4', models.ImageField(blank=True, null=True, upload_to='product')),
                ('product_image5', models.ImageField(blank=True, null=True, upload_to='product')),
                ('phone_number', models.CharField(max_length=20)),
                ('product_address', models.CharField(max_length=100)),
                ('product_quantity', models.CharField(max_length=8)),
                ('about_product', models.TextField(blank=True)),
                ('russian_product_name', models.CharField(blank=True, max_length=70)),
                ('is_vip', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('delivery', models.BooleanField(default=False)),
                ('credit', models.BooleanField(default=False)),
                ('liked', models.BooleanField(default=False)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('product_slug', models.SlugField(default='onum')),
                ('product_adder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_products', to=settings.AUTH_USER_MODEL, to_field='phone_number')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', to_field='category_name')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
