# Generated by Django 4.0.5 on 2023-04-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_client_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='about_product',
            new_name='product_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='product',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='russian_product_name',
        ),
    ]
