# Generated by Django 4.0.5 on 2023-04-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_dukan'),
    ]

    operations = [
        migrations.AddField(
            model_name='dukan',
            name='product_image6',
            field=models.ImageField(blank=True, null=True, upload_to='DukanProductImages'),
        ),
        migrations.AddField(
            model_name='dukan',
            name='product_image7',
            field=models.ImageField(blank=True, null=True, upload_to='DukanProductImages'),
        ),
        migrations.AddField(
            model_name='dukan',
            name='product_image8',
            field=models.ImageField(blank=True, null=True, upload_to='DukanProductImages'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image6',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image7',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image8',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='dukan',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='DukanProductImages'),
        ),
        migrations.AlterField(
            model_name='dukan',
            name='product_image2',
            field=models.ImageField(blank=True, null=True, upload_to='DukanProductImages'),
        ),
        migrations.AlterField(
            model_name='dukan',
            name='product_image3',
            field=models.ImageField(blank=True, null=True, upload_to='DukanProductImages'),
        ),
        migrations.AlterField(
            model_name='dukan',
            name='product_image4',
            field=models.ImageField(blank=True, null=True, upload_to='DukanProductImages'),
        ),
        migrations.AlterField(
            model_name='dukan',
            name='product_image5',
            field=models.ImageField(blank=True, null=True, upload_to='DukanProductImages'),
        ),
    ]
