# Generated by Django 4.1.7 on 2023-05-23 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_banners'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.RenameField(
            model_name='banners',
            old_name='category',
            new_name='category_id',
        ),
    ]
